CREATE TABLE [dbo].[tbl_TimeZone](
	[TimeZoneID] [int] NOT NULL,
	[CountryID] [int] NOT NULL,
	[TimeZone] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_tbl_TimeZone] PRIMARY KEY CLUSTERED 
(
	[TimeZoneID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


