//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF.BASE.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XF.BASE.Assets.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string ActualText {
            get {
                return ResourceManager.GetString("ActualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endline QC Mobile Application.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg..
        /// </summary>
        public static string AverageShortText {
            get {
                return ResourceManager.GetString("AverageShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string AverageText {
            get {
                return ResourceManager.GetString("AverageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colours.
        /// </summary>
        public static string ColoursText {
            get {
                return ResourceManager.GetString("ColoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A PART TO DISPLAY COLOURS.
        /// </summary>
        public static string ColoursValidation {
            get {
                return ResourceManager.GetString("ColoursValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string ColourText {
            get {
                return ResourceManager.GetString("ColourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string ConstructionText {
            get {
                return ResourceManager.GetString("ConstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@worldfashionexchange.com.
        /// </summary>
        public static string ContactUsEmailLink {
            get {
                return ResourceManager.GetString("ContactUsEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © World Fashion exchange All Rights Reserved..
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateAccountLink {
            get {
                return ResourceManager.GetString("CreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cum..
        /// </summary>
        public static string CumulativeShortText {
            get {
                return ResourceManager.GetString("CumulativeShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative.
        /// </summary>
        public static string CumulativeText {
            get {
                return ResourceManager.GetString("CumulativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerText {
            get {
                return ResourceManager.GetString("CustomerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Garment.
        /// </summary>
        public static string DefectGarmentText {
            get {
                return ResourceManager.GetString("DefectGarmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Rate.
        /// </summary>
        public static string DefectRateText {
            get {
                return ResourceManager.GetString("DefectRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect .
        /// </summary>
        public static string DefectText {
            get {
                return ResourceManager.GetString("DefectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eff..
        /// </summary>
        public static string EfficiencyShortText {
            get {
                return ResourceManager.GetString("EfficiencyShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string EfficiencyText {
            get {
                return ResourceManager.GetString("EfficiencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END SHIFT.
        /// </summary>
        public static string EndShiftButton {
            get {
                return ResourceManager.GetString("EndShiftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-Factory Date.
        /// </summary>
        public static string ExFactoryDateText {
            get {
                return ResourceManager.GetString("ExFactoryDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        public static string FailureMsgText {
            get {
                return ResourceManager.GetString("FailureMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password ?.
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garments .
        /// </summary>
        public static string GarmentsText {
            get {
                return ResourceManager.GetString("GarmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line ID: .
        /// </summary>
        public static string LineIDText {
            get {
                return ResourceManager.GetString("LineIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch break.
        /// </summary>
        public static string LunchBreakText {
            get {
                return ResourceManager.GetString("LunchBreakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark on Garment.
        /// </summary>
        public static string MarkOnGarmentText {
            get {
                return ResourceManager.GetString("MarkOnGarmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DEFECTS TO DISPLAY GARMENT.
        /// </summary>
        public static string MarkOnGarmValidation {
            get {
                return ResourceManager.GetString("MarkOnGarmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string MeetingText {
            get {
                return ResourceManager.GetString("MeetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Garment.
        /// </summary>
        public static string NewGarmentText {
            get {
                return ResourceManager.GetString("NewGarmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feed.
        /// </summary>
        public static string NoFeedText {
            get {
                return ResourceManager.GetString("NoFeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Start Date.
        /// </summary>
        public static string OrderStartDateText {
            get {
                return ResourceManager.GetString("OrderStartDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherText {
            get {
                return ResourceManager.GetString("OtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string PartsText {
            get {
                return ResourceManager.GetString("PartsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string PartText {
            get {
                return ResourceManager.GetString("PartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string PassedText {
            get {
                return ResourceManager.GetString("PassedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass .
        /// </summary>
        public static string PassText {
            get {
                return ResourceManager.GetString("PassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSE.
        /// </summary>
        public static string PauseButton {
            get {
                return ResourceManager.GetString("PauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string PausedText {
            get {
                return ResourceManager.GetString("PausedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcs..
        /// </summary>
        public static string PiecesShortText {
            get {
                return ResourceManager.GetString("PiecesShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        public static string PiecesText {
            get {
                return ResourceManager.GetString("PiecesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order No..
        /// </summary>
        public static string PoNumberText {
            get {
                return ResourceManager.GetString("PoNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        public static string PoQtyText {
            get {
                return ResourceManager.GetString("PoQtyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Purchase Orders.
        /// </summary>
        public static string PoSearchBarText {
            get {
                return ResourceManager.GetString("PoSearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POs.
        /// </summary>
        public static string POsText {
            get {
                return ResourceManager.GetString("POsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductText {
            get {
                return ResourceManager.GetString("ProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuantityText {
            get {
                return ResourceManager.GetString("QuantityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string QuePromptText {
            get {
                return ResourceManager.GetString("QuePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RejectedText {
            get {
                return ResourceManager.GetString("RejectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject .
        /// </summary>
        public static string RejectText {
            get {
                return ResourceManager.GetString("RejectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ResumeButton {
            get {
                return ResourceManager.GetString("ResumeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework Garment.
        /// </summary>
        public static string ReworkGarmentText {
            get {
                return ResourceManager.GetString("ReworkGarmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE DEFECT.
        /// </summary>
        public static string SaveDefectButton {
            get {
                return ResourceManager.GetString("SaveDefectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Defects.
        /// </summary>
        public static string SelectDefectsText {
            get {
                return ResourceManager.GetString("SelectDefectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A LOCATION/OPERATION TO DISPLAY DEFECTS.
        /// </summary>
        public static string SelectDefectsValidation {
            get {
                return ResourceManager.GetString("SelectDefectsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Defect.
        /// </summary>
        public static string SelectDefectTitle {
            get {
                return ResourceManager.GetString("SelectDefectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location/Operation.
        /// </summary>
        public static string SelectLocOrOpText {
            get {
                return ResourceManager.GetString("SelectLocOrOpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A TYPE TO DISPLAY LOCATIONS/OPERATIONS.
        /// </summary>
        public static string SelectLocOrOpValidation {
            get {
                return ResourceManager.GetString("SelectLocOrOpValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reason.
        /// </summary>
        public static string SelectReasonText {
            get {
                return ResourceManager.GetString("SelectReasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Reject.
        /// </summary>
        public static string SelectRejectTitle {
            get {
                return ResourceManager.GetString("SelectRejectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        public static string SelectTypeText {
            get {
                return ResourceManager.GetString("SelectTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shift.
        /// </summary>
        public static string ShiftDropdownText {
            get {
                return ResourceManager.GetString("ShiftDropdownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string ShiftText {
            get {
                return ResourceManager.GetString("ShiftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string SizesText {
            get {
                return ResourceManager.GetString("SizesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A COLOUR TO DISPLAY SIZES.
        /// </summary>
        public static string SizesValidation {
            get {
                return ResourceManager.GetString("SizesValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SizeText {
            get {
                return ResourceManager.GetString("SizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Order.
        /// </summary>
        public static string SoNumberText {
            get {
                return ResourceManager.GetString("SoNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   THIS PO IS ON PRIORITY, PLEASE START WITH FOCUS ON MEASUREMENTS  .
        /// </summary>
        public static string SoPoInstructionText {
            get {
                return ResourceManager.GetString("SoPoInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Sales Orders.
        /// </summary>
        public static string SoSearchBarText {
            get {
                return ResourceManager.GetString("SoSearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START INSPECTION.
        /// </summary>
        public static string StartInspectionButton {
            get {
                return ResourceManager.GetString("StartInspectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string StyleText {
            get {
                return ResourceManager.GetString("StyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Saved Successfully.
        /// </summary>
        public static string SuccessMsgText {
            get {
                return ResourceManager.GetString("SuccessMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string TargetText {
            get {
                return ResourceManager.GetString("TargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDO.
        /// </summary>
        public static string Undo5Button {
            get {
                return ResourceManager.GetString("Undo5Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name.
        /// </summary>
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washroom.
        /// </summary>
        public static string WashroomText {
            get {
                return ResourceManager.GetString("WashroomText", resourceCulture);
            }
        }
    }
}
